manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: rwyattwalker
      url-base: https://github.com/rwyattwalker
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-mod
      remote: rwyattwalker                     
      revision: main                      
  self:
    path: config
